{% set name = "esi-utils-colors" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/esi_utils_colors-{{ version }}.tar.gz
  sha256: 91a69b6201558454db61ee73292c959781730adb88afa3f4f5575a96c0308435

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.1.0
    - numpy >=1.26
    - pandas >=1.0

test:
  imports:
    - esi_utils_colors
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/esi-utils-colors/
  summary: USGS Earthquake Impact Utilities for Colors
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
